# paths:
#   /api/posts/get:
#     get:
#       tags:
#         - Post
#       summary: 게시글 전체 조회
#       response:
#       '200':
#           description: 게시글 목록 조회 성공
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   $ref: '#/components/schemas/Post'
#         '500':
#           description: 서버 에러
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/Error'

      