openapi: 3.0.3
info:
  title: SMU_UMC_MINI_PROJECT - Swagger
  description: SMU_UMC_MINI_PROJECT - Swagger입니다.
paths:
  /api/posts/get:
    get:
      tags:
        - Posts
      summary: 게시글 전체 조회
      description: 게시글 전체 조회하기
      responses:
        '200':
          description: 게시글 전체 조회 성공!
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: '60d21b4667d0d8992e610c85'
                    title:
                      type: string
                      example: '첫번째 게시글'
                    content:
                      type: string
                      example: '이것은 첫번째 게시글의 내용입니다.'
                    createdAt:
                      type: string
                      format: date-time
                      example: '2023-06-19T12:34:56Z'
                    updatedAt:
                      type: string
                      format: date-time
                      example: '2023-06-19T12:34:56Z'
        '500':
          description: 서버 오류
  /api/posts/get/{post_id}:
    get:
      tags:
        - Posts
      summary: 게시글 1개 조회
      description: 게시글 ID로 게시글 1개 조회하기
      responses:
        '200':
          description: 게시글 1개 조회 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: '60d21b4667d0d8992e610c85'
                  title:
                    type: string
                    example: '첫번째 게시글'
                  content:
                    type: string
                    example: '이것은 첫번째 게시글의 내용입니다.'
                  createdAt:
                    type: string
                    format: date-time
                    example: '2023-06-19T12:34:56Z'
                  updatedAt:
                    type: string
                    format: date-time
                    example: '2023-06-19T12:34:56Z'
        '404':
          description: 게시글을 찾을 수 없음
        '500':
          description: 서버 오류
  /api/posts/patch/{post_id}:
    patch:
      tags:
        - Posts
      summary: 게시글 수정
      description: 게시글 ID로 게시글 수정하기
      parameters:
        - name: post_id
          in: path
          required: true
          description: 수정할 게시글의 ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: '수정된 게시글 제목'
                content:
                  type: string
                  example: '이것이 수정된 게시글의 내용입니다.'
      responses:
        '200':
          description: 게시글 수정 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: '60d21b4667d0d8992e610c85'
                  title:
                    type: string
                    example: '수정된 게시글 제목'
                  content:
                    type: string
                    example: '이것은 수정된 게시글의 내용입니다.'
                  createdAt:
                    type: string
                    format: date-time
                    example: '2023-06-19T12:34:56Z'
                  updatedAt:
                    type: string
                    format: date-time
                    example: '2023-06-19T12:34:56Z'
        '404':
          description: 게시글을 찾을 수 없음
        '500':
          description: 서버 오류
  /api/posts/delete/{post_id}:
    delete:
      tags:
        - Posts
      summary: 게시글 삭제
      description: 게시글 ID로 게시글 삭제하기
      parameters:
        - name: post_id
          in: path
          required: true
          description: 삭제할 게시글의 ID
          schema:
            type: string
      responses:
        '200':
          description: 게시글 삭제 성공!
        '404':
          description: 게시글을 찾을 수 없음
        '500':
          description: 서버 오류
  /api/posts/create:
    post:
      tags:
        - Posts
      summary: 게시글 생성
      description: 게시글 생성하기
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: '새로운 게시글 제목'
                content:
                  type: string
                  example: '이것이 새로운 게시글의 내용입니다.'
      responses:
        '201':
          description: 게시글 생성 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: '60d21b4667d0d8992e610c89'
                  title:
                    type: string
                    example: '새로운 게시글 제목'
                  content:
                    type: string
                    example: '이것은 새로운 게시글의 내용입니다.'
                  createdAt:
                    type: string
                    format: date-time
                    example: '2023-06-19T12:34:56Z'
                  updatedAt:
                    type: string
                    format: date-time
                    example: '2023-06-19T12:34:56Z'
        '404':
          description: 게시글을 찾을 수 없음
        '500':
          description: 서버 오류
